services:
  # ────────── Payload CMS (dev) ──────────
  payload:
    image: node:20-alpine # stay up to date
    working_dir: /home/node/app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app # live code mount
      - node_modules:/home/node/app/node_modules
    command: >
      sh -c "
        corepack enable && \
        corepack prepare pnpm@9.1.2 --activate && \
        pnpm install && \
        pnpm dev
      "
    environment:
      MONGODB_URI: mongodb://mongo:27017/wearpact
      PAYLOAD_SECRET: devsecret
    depends_on:
      - mongo
    env_file:
      - .env

  # ────────── MongoDB ──────────
  mongo:
    image: mongo:7
    container_name: wearpact-mongo
    restart: unless-stopped
    ports:
      - '27017:27017' # → localhost:27017
    environment:
      MONGO_INITDB_DATABASE: wearpact
    command: ['--storageEngine=wiredTiger']
    volumes:
      - mongo_data:/data/db
    logging:
      driver: 'none'

volumes:
  mongo_data: # <-- defined correctly now
  node_modules:
